### ISSUE TITLE
[Bug] `pueue edit` does not save changes

### ISSUE THREAD

**Issue by theutz** [Nukesor/pueue#580] opened 2024-11-29 10:49 UTC
### Describe the bug

If i use `pueue edit 1` to edit the command for task 1, my `$EDITOR` opens and is filled with the content of the command. But when I save and exit my editor, the command is unchanged.

### Steps to reproduce

```bash
pueue add -s -- 'while tldr --update; do gum log -t layout -s done code $?; sleep 5; done'
pueue edit 1
```

In my editor, changed the sleep duration from `5` to `10`, then

```bash
pueue status
```

Shows the changes have not been saved. Repeated invocations of the command confirm this, as well as the timestamps from within the command.

### Operating system

macOS Sequoia

### Pueue version

v3.4.1

### Additional context

I've installed `pueue` via `cargo` via [mise](https://mise.jdx.dev). Not sure if that'd be relevant.

**Comment by Nukesor** [comment] 2024-11-29 18:21
Can you check/share the logs of both the daemon and the client?

You can get them by adding a `-vvv` after `pueue` and `pueued`

**Comment by Nukesor** [comment] 2024-12-03 12:57
Ping @theutz

**Comment by Nukesor** [comment] 2024-12-03 16:51
Interesting. So the issue is really the client. The communication between the daemon and the client looks exactly as expected.

And the client also doesn't seem to fail to read the data back from disk.
So feels a bit as if your editor doesn't save the changes to disk before existing. I'm not sure if I can do much more debugging from here :sweat_smile:

**Comment by theutz** [comment] 2024-12-03 17:42
Yeah, that makes sense. And you're right, if I run `EDITOR=nano pueue edit 0`, the changes are shown.

Oddly enough, when I run it with `EDITOR=vim` or `EDITOR="nvim --clean"`, which provides a clean vim config, the problem persists. Very weird.

Thanks for the help, though!

**Comment by Nukesor** [comment] 2024-12-03 18:45
Curious. I'm using vim myself for editing so that really shouldn't be an issue with vim...

**Comment by theutz** [comment] 2024-12-03 18:50
Excellent idea. And, interestingly enough, the changes do show up in the temporary file if I inspect it directly, yeah. So, the plot thickens... :D

**Comment by Nukesor** [comment] 2024-12-19 21:46
Did you figure out what the issue was :D?  

If it's ok for you, I would go ahead and close this issue as this seems to be problem with your setup  :)

**Comment by theutz** [comment] 2024-12-19 22:38
I never did figure it out! I think you can go ahead and close this.

**Closed** 2024-12-20 10:51 UTC
Labels: t: Bug, o: MacOS

**Comment by dkmar** [comment] 2025-03-12 19:54
Quick note. Some editors need to be opened with a flag to have the shell wait on edits. For zed I have to do `EDITOR='zed --wait' pueue edit 18 19 20`, otherwise the command exits immediately before edits are made (and saved).
