### ISSUE TITLE
pueue kill -k doesn't work

### ISSUE THREAD

**Issue by mgoral** [Nukesor/pueue#33] opened 2017-02-18 11:40 UTC
```
$ pueue status
Daemon: running

 Index  Status   Code  Command     Path                   Start  End
-----------------------------------------------------------------------
 #0     running        make serve  /home/virgo/code/blog  12:09
 #1     done     0     ls          /home/virgo            12:07  12:07

$ pueue kill -k 0
No running process with this key.
```

However, it does "something", because after running it, the old process is spawned again and process' start time is updated:

```
$ pueue add "sleep 100"
$ ps aux | ag -i sleep
virgo    21381  0.0  0.0   4336   728 ?        S    12:19   0:00 /bin/sh -c sleep 100
virgo    21382  0.0  0.0   5808   692 ?        S    12:19   0:00 sleep 100
$ pueue status
Daemon: running

 Index  Status   Code  Command     Path                   Start  End
-----------------------------------------------------------------------
 #0     running        sleep 100   /home/virgo/code/blog  12:19

$ pueue kill -k 0
No running process with this key.

$ ps aux | ag -i sleep
virgo    21382  0.0  0.0   5808   692 ?        S    12:19   0:00 sleep 100
virgo    26184  0.0  0.0   4336   728 ?        S    12:20   0:00 /bin/sh -c sleep 100
virgo    26185  0.0  0.0   5808   680 ?        S    12:20   0:00 sleep 100

$ pueue status
Daemon: running

 Index  Status   Code  Command     Path                   Start  End
-----------------------------------------------------------------------
 #0     running        sleep 100   /home/virgo/code/blog  12:20
```

It clearly shows that parent shell (the one from calling subprocess with `shell=True`) of sleep command is indeed killed, but shell itself isn't (and new command is spawned, which is another bug in my opinion). Probably that's because the process itself is killed, not the whole process group (`os.kill()` vs `os.killpg()`). However, using `psutil` for process management is more bulletproof so I'd suggest using it instead: http://stackoverflow.com/questions/6549669/how-to-kill-process-and-child-processes-from-python

**Comment by Nukesor** [comment] 2017-02-18 14:53
Actually this was wanted behaviour, until i added the `stash` command.
The daemon kills the process and sets the status to `queued`. Thereby it'll be restarted instantly on the next tick.
I'm just releasing an update with the new `stash` command. The new behaviour is: If a process is stopped or killed, it'll be stashed.

I'll look into the psutil post of yours anyway :+1:

**Comment by mgoral** [comment] 2017-02-18 16:05
Well, the problem still persists, even with stash: the running process isn't killed, only its parent process (/bin/sh) is. It's less astonishing now because the new process isn't started right away, but it will be when stashed command will be restarted. The old process is orphaned however and is no longer tracked by pueue and will continue to run until it terminates itself or is killed by a user.

**Comment by mgoral** [comment] 2017-02-18 16:08
Oh, and of course, the print "No running process with this key" is confusing, because pueue actually finds and does something with process specified by `-k`.

**Comment by Nukesor** [comment] 2017-02-21 20:44
Ok, I'll look into using psutil soon.

**Comment by Nukesor** [comment] 2017-03-03 21:57
I just tried to recreate your scenario, but it looks surprisingly different on my machine:
```
⌁ [nuke:~] % pst
Daemon: running

Queue is empty

⌁ [nuke:~] % pueue add sleep 100
Command added
⌁ [nuke:~] % ps aux | grep sleep
nuke     18843  0.0  0.0   5816   656 ?        S    22:49   0:00 sleep 100
nuke     18907  0.0  0.0  10760  2112 pts/2    S+   22:49   0:00 grep --color=auto sleep
⌁ [nuke:~] % pueue kill -k 0
No running process with this key.
⌁ [nuke:~] % pst
Daemon: running

 Index  Status   Code  Command    Path        Start  End 
---------------------------------------------------------
 #0     stashed        sleep 100  /home/nuke             

⌁ [nuke:~] % ps aux | ag -i sleep
nuke     19104  0.0  0.0  13312  1020 pts/2    S+   22:50   0:00 ag -i sleep
⌁ [nuke:~] % 
```
It's kind of weird, as i don't see the `/bin/sh -c sleep 100` process. There seems to be no real parent process for me. Maybe there is a different behaviour of subprocesses with `shell=True` for different Python versions?
`ps auxf` shows `sleep 100` as a direct child process of the daemon.
```
nuke      1040  0.0  0.2 104392 23912 ?        Ss   Mar02   0:05  \_ /usr/bin/python /usr/bin/pueue --no-daemon
nuke     19642  0.0  0.0   5816   692 ?        S    22:54   0:00  |   \_ sleep 100
```


The `No running process with this key` message was indeed a bug, this will be fixed with the next release.

**Comment by Nukesor** [comment] 2017-03-04 10:42
Could you post the `ps auxf` output of you machine?

**Comment by mgoral** [comment] 2017-03-04 13:23
> Could you post the `ps auxf` output of you machine?

Sure, nothing extraordinary here:

```
$ pueue --no-daemon
$ pueue add "sleep 1000"
$ ps auxf
virgo    11407  0.3  0.0  43096  5684 pts/5    Ss   14:17   0:00  \_ -zsh
virgo    12032  0.2  0.1  42320 13920 pts/5    S+   14:18   0:00  |   \_ /usr/bin/python3 /home/virgo/.local/bin/pueue --no-daemon
virgo    12244  0.0  0.0   4288   756 pts/5    S+   14:19   0:00  |       \_ /bin/sh -c sleep 1000
virgo    12245  0.0  0.0   5840   704 pts/5    S+   14:19   0:00  |           \_ sleep 1000

**Comment by mgoral** [comment] 2017-03-04 13:25
Sure, nothing extraordinary here:

```
$ pueue --no-daemon
$ pueue add "sleep 1000"
$ ps auxf
virgo    11407  0.3  0.0  43096  5684 pts/5    Ss   14:17   0:00  \_ -zsh
virgo    12032  0.2  0.1  42320 13920 pts/5    S+   14:18   0:00  |   \_ /usr/bin/python3 /home/virgo/.local/bin/pueue --no-daemon
virgo    12244  0.0  0.0   4288   756 pts/5    S+   14:19   0:00  |       \_ /bin/sh -c sleep 1000
virgo    12245  0.0  0.0   5840   704 pts/5    S+   14:19   0:00  |           \_ sleep 1000
```

**Comment by Nukesor** [comment] 2017-03-05 18:56
Ok. The shell parent process only spawns if there is any shell specific syntax in the command string, at least on my machine.
I managed to reproduce the problem and finally understood the significance of this bug. Thanks for reporting!
The bug should be resolved and will be in the next release as well!

**Closed by Nukesor** 2017-03-05 18:56 UTC
