### ISSUE TITLE
[BUG] pueue show and log fail "randomly"

### ISSUE THREAD

**Issue by Lesstat** [Nukesor/pueue#63] opened 2020-02-03 13:28 UTC
**Describe the bug**
When I use `pueue log <task_id>` or `pueue show <task_id>`, I get:
```
Error: control character (\u0000-\u001F) found while parsing a string at line 1 column 89537
```
On other times (more rarely) I get the output of my command.

**To Reproduce**
1. I started pueued
2. I added a task with `pueue add -- ./build/multi-ch -t <graph-file> -p 99.8 -w <output-file> --stats` (my own [code](https://github.com/Lesstat/multi-ch-constructor) that produces lots of output ...)
3. Then I did `pueue show 1`

**Expected behavior**
See the output of the command <task_id>.

**Additional context**
- Operating System: Archlinux
- Pueue version: 0.1.5

**Praise**
pueue is an awesome tool that made my life a bit better by using it just today :)

**Comment by Nukesor** [comment] 2020-02-03 14:23
Thanks for the bug report and the praise :)

I stumbled upon a similar issue, when I used the wrong size of TCP packets.
Back then, the stream failed due to packets being too big, which resulted in truncated and malformed JSON payloads.

`column 89537` indicates, that it's most likely not the same TCP packet problem, since 90kb were already transferred correctly. 

One thing you could do to help me debug the output:

Run `pueue -vvv show 1`. This should show very detailed information on what's being received right now.

If the JSON output looks correct (E.g. it properly closes all brackets at the end and isn't truncated), this isn't a TCP problem.

In that case, there is something in your process' output that isn't properly escaped by `serde_json` and breaks the JSON parsing logic.

**Comment by Lesstat** [comment] 2020-02-03 14:57
Your welcome ;)

I have attached the output after a failure. Looks like incomplete data to me.
I'm sorry that the output is rather long. I am not sure if I can reproduce it with a shorter output ....

[output.txt](https://github.com/Nukesor/pueue/files/4148491/output.txt)

**Comment by Nukesor** [comment] 2020-02-03 15:14
Ok, that's most likely a transmission problem.
Well, I'll try to reproduce and debug this. This might take some time, though.
I won't have much spare time in the next few days :)

Thanks for the detailed information!

**Comment by Lesstat** [comment] 2020-02-03 20:17
If I can provide any more info to help, let me know!
Otherwise, take your time :)

**Comment by Nukesor** [comment] 2020-02-04 00:10
Ok.
I have no idea what's going on.
Just 5 minutes ago, I was capable of reproducing the bug, with a 70%-80% probability when running a test. Now it just won't fail.

Here's what I found out so far:
- The payload is properly encoded

- When sending the `a` character 100.000 times, it will always fail with the same error message you got: `control character (\u0000-\u001F) found while parsing a string at line 1 column 89537`
- The client receives the exact amount of bytes that should be actually send by the daemon. However, somehow the byte payload get's corrupted.
- In between all the normal `a` bytes, there is a chunk of `0` bytes, which then kill the `json_decoder`, since a `0` byte is a json control character. Until now, this `0` chunk had either 465 bytes or 232 bytes long.

I'm super confused and curious. Why is the `0` byte block always at the same position? Why has it two differen size?s Why does this only happen sometimes?

**Comment by Nukesor** [comment] 2020-02-04 19:41
Async-std issue:
https://github.com/async-rs/async-std/issues/698

**Closed** 2020-02-05 21:18 UTC
Labels: bug
