### ISSUE TITLE
[BUG] status was wrong when command contains pipes

### ISSUE THREAD

**Issue by wfxr** [Nukesor/pueue#136] opened 2020-11-12 02:36 UTC
**Describe the bug**

As the title says.

**To Reproduce**

```bash
$ pueue add 'cat /dev/urandom | md5sum &>/dev/null'
New task added (id 0).

$ pueue status
Default queue (1 parallel): running
────────────────────────────────────────────────────────────────────────────────────────────────────
 Index   Status    Exitcode   Command                                 Path            Start   End
════════════════════════════════════════════════════════════════════════════════════════════════════
 0       Success   0          cat /dev/urandom | md5sum &>/dev/null   /home/user   10:29   10:29

$ ps aux | grep -P '(cat|md5sum)' | grep -v grep
user   66427 91.9  0.0   8072   820 ?        R    10:29   1:31 cat /dev/urandom
user   66428 34.7  0.0   7944   836 ?        S    10:29   0:34 md5sum

```

**Expected behavior**

Status should be `running`.

**Additional context**
- Operating System: Ubuntu 18.04.5 LTS x86_64
- Pueue version: Pueue client 0.8.1

**Comment by Nukesor** [comment] 2020-11-12 17:49
This is weird. I'm not able to reproduce the behavior either.

```
[nuke:~] 130 % pueue add 'sh -c cat /dev/urandom | md5sum &>/dev/null' && sleep 10 && pueue status    
New task added (id 0).
Default queue (2 parallel): running
─────────────────────────────────────────────────────────────────────────────────────────────────────
 Index   Status    Exitcode   Command                                       Path         Start   End 
═════════════════════════════════════════════════════════════════════════════════════════════════════
 0       Running              sh -c cat /dev/urandom | md5sum &>/dev/null   /home/nuke   18:43       
─────────────────────────────────────────────────────────────────────────────────────────────────────
[nuke:~] % 
```

Tasks will only finish successfully, if the process completed AND exited with `0`.
It looks like the shell somehow detached the underlying processes and exited early..?

There already was some similar weird shell behavior in an earlier issue. Back then, a user noticed that `sh -c $COMMAND` sometimes spawn the command itself instead of spawning the shell first and the command as a child of that shell.

Could you try to run `sh -c "cat /dev/urandom | md5sum &>/dev/null"` and check, whether this detaches the process?

This really shouldn't happen.
The fact that I'm unable to reproduce this on my system, suggests that this is some whacky shell process spawning behavior.

**Comment by Nukesor** [comment] 2020-11-12 18:03
I just double-checked via `ps aux --forest`.

Command run in pueue:
```
nuke       40873  0.0  0.0 1021148 5492 ?        Sl   18:51   0:00 pueued
nuke       41558  0.0  0.0   7188  3088 ?        S    18:53   0:00  \_ sh -c cat /dev/urandom | md5sum &>/dev/null
nuke       41559 97.6  0.0   5472   728 ?        R    18:53   6:22      \_ cat /dev/urandom
nuke       41560  6.4  0.0   8436  1628 ?        S    18:53   0:25      \_ md5sum
```

Command run via Shell
```
nuke       42383  0.1  0.1 685364 33736 ?        Sl   18:58   0:00 termite
nuke       42388  0.1  0.0  11740  7820 pts/2    Ss   18:58   0:00  \_ /usr/bin/zsh
nuke       43114  0.0  0.0   7188  2904 pts/2    S+   18:58   0:00      \_ sh -c cat /dev/urandom | md5sum &>/dev/null
nuke       43115 98.8  0.0   5472   664 pts/2    R+   18:58   1:41          \_ cat /dev/urandom
nuke       43116  3.7  0.0   8436  1568 pts/2    S+   18:58   0:03          \_ md5sum
```

Please check, if your `cat` and `md5sum` are still children of `pueue` or if they're detached.

**Comment by wfxr** [comment] 2020-11-13 03:15
@Nukesor Thanks for your very detailful explanation.

Your guess is right. On my test machine (ubuntu 18.04) `sh -c "cat /dev/urandom | md5sum &>/dev/null"` always detaches from the shell. But on the other machine (arch latest) this command does not detach and `pueue` also works as expected.

**Comment by wfxr** [comment] 2020-11-13 03:49
I found out where the problem is. It's about version of `sh`.

`sh` with old version does not support `&>` syntax to redirect both stdout and stderr. So in `&` in command `sh -c "cat /dev/urandom | md5sum &>/dev/null"` will be regarded as `&` operator and it put the process into background. `sh -c 'cat /dev/urandom | md5sum >/dev/null 2>&1'` works without problem.

The fact is that `sh` on arch (version 5+ 2013) and osx (version 3+ 2007) have already support `&>` but on ubuntu 18.04 it even does not support `--version` option. but at the bottom of `man sh` it shows a very old date `January 19, 2003`.

**Comment by Nukesor** [comment] 2020-11-13 12:57
Wow :D

To be honest, I'm not sure if Pueue can handle something like this.
We rely on the fact, that processes stick to their spawning shell. Otherwise, there's no way to track those processes...

2003 is also an insanely old shell version for an Linux Distro released in 2018 :smile: 

I'll keep this issue open, maybe someone comes up with a good idea on how to handle this.
Until then, I'll probably add a section to the wiki about this.

Thanks a lot for the thorough investigation!

**Comment by Nukesor** [comment] 2020-11-13 13:03
I just thought about something.
Even if we could track the children of those processes, working with those processes instead of the shell process could lead to problems in other areas.

For instance, right now users can intentionally detach processes into the background, by simply writing `sleep 10 &`.
The task will finish instantly and this is completely expected and wanted behavior.

If we want to track unintentionally detached processes from legacy shells, we would have to have a mechanism, which allows us to differentiate between those and intentionally detached processes...
This definitely adds another layer of complexity to this whole Subject

**Comment by Nukesor** [comment] 2020-11-13 13:19
It's probably the best to not handle this inside of Pueue at all.

After all, this only occurs due to users expecting a certain language feature, which doesn't exist and get's misinterpreted.

I'll definitely add section to the wiki though.

**Closed** 2020-11-13 14:25 UTC
Labels: bug

**Comment by wfxr** [comment] 2020-11-14 01:35
Sorry for the late reply. I agree with your opinion that pueue should not add compatibility for old version of sh. Users can choose the old way to do redirect to make sure the expected behavior.

I'm now thinking another thing. Should pueue prefer to use user's login shell to run the command? So that we can get the same 
 shell and environment variables. After all we always expect that the behavior of the command running by pueue be consistent with directly running it from the current shell. The initial problem can also be solved —— I think almost no one uses sh as their shell, right? Maybe we can add a parameter to explicitly specify the shell. Users can still choose sh to run the program in some cases (in scripts or need best performance etc).

**Comment by Nukesor** [comment] 2020-11-15 19:57
I agree about that, however there's an abundant amount of shell implementations out there and handling all of these could become a problem.

For instance, not all shells use the `$SHELL -c $COMMAND` pattern. Windows shells are also super weird.

We could think about users being able to specify their own startup commands:
This could be a new section in the configuration file
```
shell_command:
    - "sh"
    -  "-c"
```

This was supported by the legacy python implementation of Pueue.
However, this lead to a LOT of annoying (maintenance) problems. Users reported various issues, which were solely related to their shell configuration. 

I would like to support this in a good way, but I'm not exactly sure how to (properly) do this yet.

**Comment by Nukesor** [comment] 2020-11-15 19:59
Just take a look at the current Linux process helper code.
It only handles sh's quirks and it's already super long and ugly.

https://github.com/Nukesor/pueue/blob/master/daemon/platform/linux/process_helper.rs

Even if we would want to support multiple shells, this would require a huge amount of work that would have to be done by the community. I cannot ( and don't want to) support all those shells by my own. It'll be a lot of work.

**Comment by wfxr** [comment] 2020-11-16 02:39
@Nukesor Got it. This is not a very necessary feature. pueue is already very useful in many scenerios. Thanks for your great work!
