### ISSUE TITLE
[BUG] cargo install fails on MacOS

### ISSUE THREAD

**Issue by jlkiri** [Nukesor/pueue#226] opened 2021-08-19 03:31 UTC
**Describe the bug**

**To Reproduce**
1. `cargo install pueue`
2. Confirm the error:

```
error[E0277]: the trait bound `cli::Shell: ArgEnum` is not satisfied
   --> /Users/v_kirill/.cargo/registry/src/github.com-1ecc6299db9ec823/pueue-1.0.0/client/cli.rs:383:16
    |
383 |         shell: Shell,
    |                ^^^^^ the trait `ArgEnum` is not implemented for `cli::Shell`
    |
    = note: required by `clap::ArgEnum::from_str`

error[E0277]: the trait bound `cli::Shell: ArgEnum` is not satisfied
   --> /Users/v_kirill/.cargo/registry/src/github.com-1ecc6299db9ec823/pueue-1.0.0/client/cli.rs:383:16
    |
383 |         shell: Shell,
    |                ^^^^^ the trait `ArgEnum` is not implemented for `cli::Shell`
    |
    = note: required by `VARIANTS`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0277`.
error: could not compile `pueue`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `pueue v1.0.0`
```

**Expected behavior**
Working installation.

**Screenshots**

**Additional context**
- MacOS 11.4
- Pueue version 1.0.0

**Comment by Nukesor** [comment] 2021-08-19 09:40
This looks very much like a duplicate of https://github.com/Nukesor/pueue/issues/224

Could you try and run `cargo install` with the `--locked` flag?

**Comment by Nukesor** [comment] 2021-08-19 09:47
I also added the `--locked` parameter to the `cargo install pueue` command in the Readme.
Didn't expect this to happen on a release :D

**Closed by Nukesor** 2021-08-19 09:47 UTC
Labels: bug
