### ISSUE TITLE
Option to show only status, log of x last items or for specific ranges

### ISSUE THREAD

**Issue by ghuls** [Nukesor/pueue#167] opened 2021-01-11 10:56 UTC
Option to show only status, log of x last items or for specific ranges.

So an option like --range would be useful:

```bash
# Show log of 20 last items.
pueue log --range -20:-1
pueue log --range -20:

# Show log of item 50 till the end
pueue log --range 50:

# Show log of first 20 items.
pueue log --range 0:20
pueue log --range :20

# Show status of job 45.
pueue status --range 45
```

**Comment by Nukesor** [comment] 2021-01-13 15:33
Hmm.

To be honest, I'm not the biggest fan of this feature request.
If feels like this solves a fundamental problem that shouldn't be there to begin with

What exactly is your use-case for this?

**Comment by ghuls** [comment] 2021-01-14 13:47
How do you handle when you have e.g. hundreds of jobs from which e.g. the first 50 are already finished (as they might be from the day before), but don't want to clear them yet?

**Comment by Nukesor** [comment] 2021-01-15 00:26
Well, first of all we should think about if having hundreds of jobs is actually something Pueue should be designed for.

It has been designed for on-demand scheduling and management of shell commands.
This is something that is done manually while doing tasks on the commandline.

However, people started to use it as a task scheduler that is populated by shell scripts.
I see how this seems like a natural decision, but I'm not sure if this is the direction this project should shift to.

As soon as we start to focus on supporting hundreds of tasks, we'll need even more tools to better manage those amounts of tasks. Pueue has simply not been for designed for this scale of work.

**Comment by ghuls** [comment] 2021-01-15 10:07
I am using it directly in the shell. e.g. for rebuilding rust based command line tools if git pull for the current repo fetches new commits. Or for compiling the latest version of tools written in C or C++. Or downloading some big files, untarring/unzipping them, ...

**Comment by Nukesor** [comment] 2021-01-15 12:28
Hmm.

I assume you're already using the `group` feature to split the whole amount of task into related chunks.
So if I understand correctly, you're building your own software instead of using some kind of package manager and you're building a bunch of stuff in bursts, e.g. whenever you check your local repositories for new commits.

I got one more question. Why exactly do you want to keep those old logs? Specifically for successfully completed tasks?
Would some kind of backup-mechanism for old logs encourage you to clean your queue?

The problem is, that I'm using as a daily driver Pueue myself on a lot of occasions.
However, I didn't ever have the problem of having multiple hundred tasks in a single queue/group.

Thereby I didn't experience this form of unergonomic behavior and, to be honest, I'm still having a hard time to understand how to get there :sweat_smile:

One thing I might do differently is, that I tend to encapsulate a group of always finishing tasks into shell scripts, if those tasks manage to perfectly utilize some resource. For instance, I'm building all my local rust projects via a shell script (a simple cd && git pull && cargo install) which is then added to pueue.

Anyway, I would love to get more insight into the way you're using Pueue.

Sorry if this might seem a little annoying or interrgative. I'm just trying to perfectly understand the requirements of a feature, before I start building it.
This software is used by quite a few people after all and I took the responsibility to take care about it and maintain it.

**Comment by Nukesor** [comment] 2021-01-15 13:07
As a matter of fact, I just implemented the `--successful-only` flag for the `clean` subcommand.
Retrospectively, this is something that would have been handy in quite a few scenarios.

**Comment by Nukesor** [comment] 2021-01-15 13:13
As I think about it, it would also be pretty cool to have a `--last-lines` option for the `log` subcommand.
That way, you can take a look at the currently relevant log output of your tasks without flooding your terminal.

This should improve ergonomics of the `log` output for multiple tasks a lot.
We could even think about having this as the default as soon as multiple tasks are printed via `log`.

**Comment by Nukesor** [comment] 2021-01-15 20:46
PR to limit lines in `log` output and to change the default `log` behavior is out as well:
https://github.com/Nukesor/pueue/compare/limit_log_lines?expand=1

**Comment by Nukesor** [comment] 2021-01-18 17:29
@ghuls Do you think that any of the two proposed changes could help you in organizing your tasks?

**Comment by ghuls** [comment] 2021-01-19 09:51
This is already much better. Thanks

**Comment by Nukesor** [comment] 2021-01-19 11:44
Perfect :)
Closing for now

**Closed by Nukesor** 2021-01-19 11:44 UTC
Labels: Feature
