### ISSUE TITLE
Add a --lines option to pueue follow

### ISSUE THREAD

**Issue by devster31** [Nukesor/pueue#287] opened 2022-01-19 02:05 UTC
#### Is your feature request related to a problem?

A long running task can have a very long log file.

#### Describe the solution you'd like

`pueue follow` should have a `--lines` option like `pueue log` to allow starting the follow from the end.

#### Describe alternatives you've considered

I'm currently using `tail -f -n30 ~/.local/share/pueue/task_logs/<task_id>*` to follow the logs I'm interested in.

**Comment by Nukesor** [comment] 2022-01-19 09:20
Duplicate of https://github.com/Nukesor/pueue/pull/270

**Closed by Nukesor** 2022-01-19 09:20 UTC
