### ISSUE TITLE
Edit task environment variables

### ISSUE THREAD

**Issue by mjpieters** [Nukesor/pueue#503] opened 2024-02-26 16:55 UTC
### A detailed description of the feature you would like to see added.

Currently, you can edit three aspects of a scheduled task: the command to be run, the path where the task is run and it's label. 

Tasks have another component: the environment variables under which the command is executed. Can we have an option to edit these?

A stretch goal would be the ability to add, set or remove environment variables _across all tasks or a task group_. This lets you do things like set bandwidth limits on a whole group of tasks where the commands in those tasks honour a bandwidth limit set in an environment variable. Powerful stuff!

### Explain your usecase of the requested feature

Loads of UNIX command change their behaviour based on the environment variables that are present when they start. Sometimes, we need to change what environment variables are present for a given task, because sometimes circumstances change or we made a mistake with the env vars when the task was added.

The ability to alter environment variables across all tasks is another powerful option. This may need to be a separate command (or even a separate FR!).

### Alternatives

I've actively edited the command for tasks to add extra environment variables. This is a poor workaround however, as it is easy to accidentally alter the command itself.

**Comment by Nukesor** [comment] 2024-02-27 21:53
It's a bit of an edge-case, but I definitely see how this is a good QoL feature.

I'm thinking about the best way to do this.
My first thought would be to set the key-values directly on the commandline, especially if one wants to set multiple values at the same time (e.g. `pueue edit 0 -e KEY=value -e OTHER_KEY=othervalue`).
The behavior will then be a bit inconsistent, but I feel like editing environment variables in an editor will be pretty cumbersome as there're usually a lot of variables.

Maybe we should add a new subcommand for this? This would also make it quite easy to edit variables for groups or multiple commans, as i feel like those flags would be very confusing on the current `edit` command.

**Comment by mjpieters** [comment] 2024-03-01 16:46
Yes, the more I think about this, the more this sounds like a separate subcommand.

**Comment by Nukesor** [comment] 2024-03-10 10:35
If you like, feel free to start hacking on this :) Your contributions have always been top notch and I trust that you'll make the right design decisions ;D

**Comment by Nukesor** [comment] 2024-04-04 10:04
@activatedgeek It sounds like you could make good use of the https://github.com/Nukesor/pueue/wiki/Get-started#load-balancing feature. This would allow you to do automatic balancing on your gpus for you :)

**Comment by activatedgeek** [comment] 2024-04-04 15:16
Thank you.

My understanding was that this behavior would require me to change existing code to parse out the `PUEUE_WORKER_ID` and transform it to appropriate values of `CUDA_VISIBLE_DEVICES` (e.g. something like a round robin over the list of GPUs). To avoid going back and change internal code plumbing, it was the easiest to just modify at pueue add time.

But of course, nothing too complicated since it can be similarly plugged in by instead of calling the GPU job directly, calling another bash script that does the transform to call to the GPU job.

Another tricky scenario with the example was this series of steps, say for group `cluster1` with parallel `2` (assuming a machine with 2 GPUs with each job using 1 GPU in a round-robin manner):
```
Queue experiment 1 on cluster 1
Queue experiment 2 on cluster 1
Queue experiment 3 on cluster 1
Scheduled experiment 1 (PUEUE_WORKER_ID = 0 assigned to GPU 0)
Scheduled experiment 2 (PUEUE_WORKER_ID = 1 assigned to GPU 1)
Completed experiment 2
Scheduled experiment 3 (PUEUE_WORKER_ID = 2 assigned to GPU 0)
```

Now experiment 1 and experiment 3 both run on GPU 0, and in many of my cases with large models would lead to an out of memory error on GPU 0. Of course, this could be fixed with slightly smarter scheduling at the expense of more plumbing. This is why I took the easier route of limiting each group to schedule on a fix set of GPU IDs.

Let me know if the scenario makes sense, and if I am missing something simpler here.

**Comment by Nukesor** [comment] 2024-04-04 17:14
> My understanding was that this behavior would require me to change existing code to parse out the PUEUE_WORKER_ID and transform it to appropriate values of CUDA_VISIBLE_DEVICES (e.g. something like a round robin over the list of GPUs). 

Exactly. That's how it was designed.

> Now experiment 1 and experiment 3 both run on GPU 0, and in many of my cases with large models would lead to an out of memory error on GPU 0. Of course, this could be fixed with slightly smarter scheduling at the expense of more plumbing. This is why I took the easier route of limiting each group to schedule on a fix set of GPU IDs.

That'sa ctually not how it would work. In your example, the last line would look like this:

```
Completed experiment 2
Scheduled experiment 3 (PUEUE_WORKER_ID = 1 assigned to GPU 0)
```

The ID is not the task id, but rather the internal "worker" or rather "slot" id. As soon as a task in a queue finishes, its "slot" is freed and the next task then gets that slot.

If it doesn't work this way, this is definitely a bug! That system was specifically designed to handle your usecase. Machines/pools with a set number of limited resources, to which the tasks are then assigned in a greedy manner.

**Comment by activatedgeek** [comment] 2024-04-04 18:59
Ahaa! That makes much more sense. Thank you for clarifying. 

Let me run a quick test simulating this scenario, and will report back. I'll update the wiki with this example so that the behavior is more explicit.

**Comment by activatedgeek** [comment] 2024-04-08 21:25
Sorry for the delay. I have verified this behavior, and this actually solves my specific problem.

I also realized I missed this:

> There'll never be two concurrent tasks with the same $PUEUE_WORKER_ID in the same group.

In that case, the wiki already explains it precisely, and I will skip the wiki edit.

**Comment by Nukesor** [comment] 2024-07-04 14:03
@mjpieters I'm thinking about adding a `pueue task` command to inspect and eventually manipulate tasks.

The idea came up during https://github.com/Nukesor/pueue/issues/540.

What do you think about a `pueue task env` command to inspect the environment.
And respective `pueue task env remove $NAME` and `pueue task env set $NAME $VALUE` commands?

Is the nesting too big or is this reasonable?

**Comment by Nukesor** [comment] 2024-08-01 08:43
Ping @mjpieters

**Comment by mjpieters** [comment] 2024-08-01 12:59
I love the nesting, actually. Grouping like this can really help with command clarity. E.g. the `gh` command-line tool for GitHub has 3 levels for most commands.

I would almost say grouping is overdue for pueue; you have commands that operate on either a group or a task, which maybe could do with splitting across command groups, with aliases for backwards compatibility / ease of typing:

* `pueue task` *(aliases: `pueue t`)*
    * `add` *(aliases: `pueue add`)*
    * `remove <TASKIDS>...` *(aliases: `pueue task rm`, `pueue remove`)*
    * `switch <TASKID1> <TASKID2>` *(aliases: `pueue switch`)
    * `stash <TASKIDS>...` *(aliases: `pueue stash`)*
    * `enqueue [TASKIDS]...` *(aliases: `pueue enqueue`)*
    * `start [TASKIDS]...` *(aliases: `pueue start`)*
    * `restart [TASKIDS]...` *(aliases: `pueue task re`, `pueue restart`)*
    * `pause [TASKIDS]...` *(aliases: `pueue pause`)*
    * `kill [TASKIDS]...` *(aliases: `pueue kill`)*
    * `send <TASKID> <INPUT>` *(aliases: `pueue send`)*
    * `edit <TASKID>` *(aliases: `pueue edit`)*
    * `log [TASKIDS]...` *(aliases: `pueue log`)*
    * `follow [TASKID]` *(aliases: `pueue task fo`, `pueue follow`)*
    * `wait [TASKIDS]...` *(aliases: `pueue wait`)*
    * `env <TASKID>`
        * `set <TASKID> <ENVVAR> <VALUE>`
        * `unset <TASKID> <ENVVARS>...`
* `pueue group` *(aliases: `pueue g`)*
    * `add <GROUP>`
    * `remove <GROUPS>...` *(aliases: `pueue group rm`)*
    * `start [GROUPS]...` *(aliases: `pueue start -g/--group`, `pueue start -a/--all`)*
    * `restart [GROUPS]...` *(aliases: `pueue group re`, `pueue restart -g/--failed-in-group`, `pueue restart -a/--all`)*
    * `pause [GROUPS]...` *(aliases: `pueue pause -g/--group`, `pueue pause -a/--all`)*
    * `kill [GROUPS]...` *(aliases: `pueue kill -g/--group`, `pueue kill -a/--all`)*
    * `status <GROUPS>...` *(aliases: `pueue status -g/--group`)*
    * `wait [GROUPS]...` *(aliases: `pueue wait -g/--group`, `pueue wait -a/--all`)*
    * `clean <GROUPS>...` *(aliases: `pueue group cleanup`, `pueue group clear`, `pueue clean -g/--group`)*
    * `reset [GROUPS]...` *(aliases: `pueue reset -g/--group`)
    * `parallel [GROUP] [PARALLEL_TASKS]` *(aliases: `pueue parallel -g/--group`)

and the following first-tier top-level commands:

* `pueue status`
* `pueue clean`
* `pueue shutdown`
* `pueue completions`
* `pueue help`

Note that for many commands that accepted a single `-g/--group` name the above structure allows for multiple groups to be named. Ditto for `pueue task env unset <ENVVARS>...` to unset multiple environment variables (but I rather name them explicitly and not default to 'all' if you don't name envvars).

**Comment by mjpieters** [comment] 2024-08-02 13:50
Fair enough; it's why I included aliases for the original top-level commands in there (as well as thinking about backwards compatibility). It could perhaps depend on how the aliases are represented when you run `pueue --help`.

**Closed** 2024-12-01 16:20 UTC
Labels: f: Help wanted, t: Feature, s: Pueue-lib, s: Daemon, s: Client

**Comment by Nukesor** [comment] 2024-12-03 12:55
I thought a lot about the CLI redesign and still really wasn't happy about any solution.
In my mind, it made the usage either unintuitive/confusing for newcomers, since there were multiple ways to do one thing. Alternatively, other solutions made the tool harder to use for the 90% usecase.

This issue was kind of blocking me and preventing the 4.0 release, which included a lot of other stuff that needed to be released, so I decided to stick to the old pattern for now and tackle this in a later release :)
