### ISSUE TITLE
Allow `~` in Pueue config paths

### ISSUE THREAD

**Issue by dadav** [Nukesor/pueue#191] opened 2021-04-10 08:32 UTC
**Describe the bug**
The documentation says you can use e.g. `$USER` or `$HOME` (shell in general) in the configuration file (https://github.com/Nukesor/pueue/wiki/Configuration). At least it seams to me like that...But this results in a literal `$HOME` directory.

**To Reproduce**
Use `pueue_directory: $HOME/.local/share/pueue` in your config.

**Expected behavior**
The daemon should resolve the path the the actual location.

**Additional context**
OS: Archlinux
pueue daemon: 0.12.1

**Comment by Nukesor** [comment] 2021-04-10 10:18
Those are example placeholders that should be replaced by the actual thing.
I see how this can be confusing.

I'm open to suggestions on how to clarify this :)

**Comment by dadav** [comment] 2021-04-10 11:26
Wouldn't it be nice to actually support variables? :)

**Comment by Nukesor** [comment] 2021-04-11 19:14
On Unix, at least the home `~` notation is supported :)

**Comment by dadav** [comment] 2021-04-12 05:39
> 
> 
> On Unix, at least the home `~` notation is supported :)

Ohhh, okay, thats all I need!!

**Comment by dadav** [comment] 2021-04-21 17:00
Hi, I just realized that there is a literal ~ in my homedir :D

**Comment by Nukesor** [comment] 2021-04-21 18:25
Wow. Yep, I'm able to reproduce that behavior.
Well, I guess `~` isn't supported after all :D .

Ok, there are a few different possible approaches:

1. First solution:

Resolve anything like `~` or similar stuff during deserialization of the configuration file.
This comes with its own caveats.

The daemon manipulates and overwrites the configuration file regularily (for instance if you add a group).
As a result, you would also have to revert the original resolving on serialization. \
But how do you know whether there originally was a `~` or a `/home/your_username/`?

I don't like this one too much.

2. Second solution:

Don't touch any strings during deserialization/serialization.
Instead all resolving/parsing would have to be done in getter functions and make all paths non-public struct members.

This is most likely the cleanest solution, but will require quite a bit of refactoring, since those paths are passed around pretty much everywhere.


If you feel like this is something you must have, feel free to start coding :D.

However, it's nothing I'll implement myself, since i haven't touched my Pueue config file in ages :D

**Comment by dadav** [comment] 2021-04-22 05:19
I never wrote a single line in rust, but I'll try :D Can't be that hard, right? *fingers crossed*

**Comment by dadav** [comment] 2021-04-28 17:06
@Nukesor The commit above and https://github.com/dadav/pueue-lib/commit/97fc46cd4caf3bde8723bd5e6921433a36242702 works for me. but I have no sense if this is how it should be done. Maybe you can have a look :)

**Comment by dadav** [comment] 2021-05-03 16:20
I'm having a hard to time understand how to solve this https://github.com/dadav/pueue-lib/blob/fix_variable_expansion/src/settings.rs#L86

It tells me the following:  `move occurs because *old_path has type std::path::PathBuf, which does not implement the Copy trait`

and the documentation tells me to:

* Try to avoid moving the variable.
* Somehow reclaim the ownership.
* Implement the `Copy` trait on the type.

BUT the `Shared` struct already has `Copy` as a trait....(https://github.com/dadav/pueue-lib/blob/fix_variable_expansion/src/settings.rs#L15)

**Comment by Nukesor** [comment] 2021-05-03 17:54
I actually got something wrong in my original review :D
I should've checked out your code and investigated it myself, sorry for any inconveniences :)

Yep, Rust is definitely a little tricky. I have the feeling that one needs to read at least half of the book and probably half a year of regular struggling.
Before that, a lot of the stuff one usually does feels super unintuitive. Especially, if one comes from non-system languages ...
Having to think about borrowing/mutability and lifetimes while coding is a huge overhead in the beginning, but after some time it feels quite natural and helps a lot to build properly structured code bases.

As someone who also comes from a Python background, I feel your struggle. Actually, Pueue's first version was built in Python :D

Back to your review.


A fixed version of your code can be found over here:
https://github.com/Nukesor/pueue/tree/fix_variable_expansion

What went wrong:

In settings.rs:80 there wasn't any to need to do `into_os_string` and no `Result` error handling was necessary.

```
pub fn into_os_string(self) -> OsString

Consumes the PathBuf, yielding its internal OsString storage.
```

Calling `into_os_string` consumes the `old_path: PathBuf` variable, which means it can no longer be used afterwards.
However, since we pass a reference to that variable, we cannot simply consume it, since it might be used after the function finished in the previous scope!

```
pub fn expand(old_path: &PathBuf) -> Result<PathBuf> {
    return Ok(PathBuf::from(tilde(&old_path.into_os_string().to_string_lossy()).into_owned()));
}
```

Becomes:
```
pub fn expand(old_path: &PathBuf) -> PathBuf {
    return PathBuf::from(tilde(&old_path.to_string_lossy()).into_owned());
}
```

state:295:31

This one was an error on my side, sorry about that.
Usually, `PathBuf` can be used in place of `Path`, as it's `An owned, mutable path (akin to String)`.
It automatically dereferences to `Path`, if needed, as it implements the ` Deref<Target = Path>`.

This `let path = Path::new(&self.settings.shared.pueue_directory());`
Can just be reduced to this `let path = self.settings.shared.pueue_directory();

I definitely need to revisit parts of the codebase, since some things are written in a more complicated manner than they need to be. (I'm still learning a lot of stuff myself)
This for instance, was overly complicated and entirely my fault.


Anyhoq, next time don't be afread to directly open a PR ;).
t makes discussions much easier and it also makes it much easier for me to properly review your code!

**Comment by dadav** [comment] 2021-05-04 05:33
Thanks for your explanation!!! I will fix it and create a PR :)

**Closed** 2021-05-11 23:02 UTC
Labels: Feature, Help wanted

**Comment by Nukesor** [comment] 2021-05-28 12:30
The release candidate is now available.
`cargo install pueue --version 1.0.0-rc.1`
