### ISSUE TITLE
[Clarification] How to quote commands with Pueue

### ISSUE THREAD

**Issue by sayanarijit** [Nukesor/pueue#182] opened 2021-02-18 07:23 UTC
First of all, please read the [getting started guide](https://github.com/Nukesor/pueue/wiki/Get-started).
Especially if you have problem with **escaping** or **wrong shell syntax**!

Otherwise feel free to go ahead :)

**Describe the bug**
pueue doesn't quote the given commands properly

**To Reproduce**
- Run `pueue add -- bash -c "sleep 3 && echo yo"`.
- The command fails.

**Expected behavior**
pueue should have run `bash -c "sleep 3 && echo yo"` instead of `bash -c sleep 3 && echo yo`.

**Screenshots**
```bash
➜  ~ pueue add -- bash -c "sleep 3 && echo yo"
New task added (id 7).

➜  ~ pueue log
┌────────────────────────────────────┐
│ Task 7:    failed with exit code 1 │
└────────────────────────────────────┘
Command: bash -c sleep 3 && echo yo
   Path: /home/sayanarijit
  Start: Thu, 18 Feb 2021 12:46:39 +0530
    End: Thu, 18 Feb 2021 12:46:39 +0530

stderr:
sleep: missing operand
Try 'sleep --help' for more information.
```

**Additional context**
- Operating System: Manjaro
- Pueue version. `Pueue client 0.12.0, Pueue daemon 0.12.0`

**Comment by Nukesor** [comment] 2021-02-18 09:18
Related and duplicate of https://github.com/Nukesor/pueue/issues/179

**Comment by Nukesor** [comment] 2021-02-18 09:19
This is explained in here:
https://github.com/Nukesor/pueue/wiki/Get-started#adding-commands

**Comment by Nukesor** [comment] 2021-02-18 09:22
In your case you have to do this:

`pueue add 'bash -c "sleep 3 && echo yo"'`

You have to do this, since pueue doesn't have any context about the command!
It get's the commands in three strings [bash, -c, sleep3 && echo yo] and there's no context, which of these should be escaped by quotes and which shouldn't.

You have to provide this context as the user.

The best way to prevent any misunderstandings, is to completely surround the finished shell command with quotes.

**Comment by Nukesor** [comment] 2021-02-18 10:10
I also updated the `[Bug]` issue template to point to the wiki.

**Closed** 2021-02-18 11:49 UTC
Labels: bug
