### ISSUE TITLE
`pueue status` --query should support filtering tasks by ID

### ISSUE THREAD

**Issue by fluffysquirrels** [Nukesor/pueue#437] opened 2023-05-21 10:22 UTC
### A detailed description of the feature you would like to see added.

1. I want `pueue status --query "id = 17"` to display the status just for the task with ID 17.
2. I want `pueue status --query "id IN (17, 24, 42)"` to display the statuses just for the tasks with ID's 17, 24, and 42. Happy to discuss alternative syntax for this, I just described how SQL represents this as a starting point.

### Explain your usecase of the requested feature

When I am checking the status of a particular task interactively or in a script, I want to see just the status for that task.

### Alternatives

Interactively with text output, this is not currently practical, I would need to read through the outputted list myself, which may contain many other tasks.

In a script I can retrieve all tasks as JSON and then extract just the task I am interested in, but:

1. This is very wasteful in terms of resources: `pueue` CLI will query the status of all tasks from `pueued`, then print the output, then my program will read and filter the output; this takes multiple serialisation and deserialisation passes to and from JSON for the status of all the tasks, which may be a long list.
2. This is still not user friendly, for what I see as a common use case.

### Additional context

I can implement this feature and submit a PR if you wish, just let me know :)

**Comment by fluffysquirrels** [comment] 2023-05-23 14:28
`pueued` also doesn't support fetching status by ID though, does it? So I can't efficiently implement this by talking to `pueued` directly either.

`pueue_lib` just has `pueue_lib::network::message::Message::Status` to ask for `pueued`'s status, which has no arguments to filter anything.

> From what I understand, you're currently writing a script that acts as a new frontend to pueued

Not really. I want to use `pueue`, it just has this feature missing IMO, so I need to use a shell script to supplement what `pueue` provides.

> `pueue` was never designed to act as a programmable interface to the `pueued` executor backend, but rather as a nice cli tool for day-to-day usage on servers

OK, well, can it not grow to fill a new role? And personally, I script every CLI tool; it's why I like to use a terminal as opposed to a GUI. This is the Unix way.

> over time, more and more features were added that allowed `pueue` to be used in such a way, but this actually goes against the architecture and vision of `pueue`! It just hasn't been built for this.

Why does the original vision matter in this context? People find `pueue` useful, and want to add new pieces to fit their use case. It can be modified and refactored so that it works better for them.

**Comment by Nukesor** [comment] 2023-05-23 20:52
> pueued also doesn't support fetching status by ID though, does it? So I can't efficiently implement this by talking to pueued directly either.

Adding something to the query language wouldn't do anything else. `pueue` currently gets the full `status` and does client-side query logic on top of it.

> Not really. I want to use pueue, it just has this feature missing IMO, so I need to use a shell script to supplement what pueue provides.

How does that look like? Your interactive script would need to retain state or at least calculate state on given ids in your logic. I'm just wondering why your wrapper knows/tracks individual ids (in a seemingly separate interface), feels like a duct-taped frontend for pueue :D. 

> OK, well, can it not grow to fill a new role? And personally, I script every CLI tool; it's why I like to use a terminal as opposed to a GUI. This is the Unix way.

It can certainly grow in another direction, but not as long as I'm maintaining it. I have a strong vision for this project, which is driven by my own ideas on how this project is supposed to look like. I accepted many ideas from the community and implemented many of them myself, even though I don't actually use most of them myself. I did so because they fit into the vision I had for the project.

The second I accept features that don't fit into the scope of the vision I have for the project, it's no longer "my" project. As a result, I'm loosing my intrinsic motivation to maintain it, which is already happening since quite some time due to the explained development in feature requests. Tinkering on this project started to feel like a chore (which is never a good sign). As the maintainer of this project, I took both the responsibility of maintaining the project as well as myself and to find an equilibrium where the majority of the community and I are happy. 

You might drop by and add a feature to Pueue, but **I** have to maintain it for years to come, do day-to-day chores, updates and refactorings when things start to get ugly due to feature creep.
Feature creep is a thing and a growing maintenance burden is considerable side-effect.

Also, as the person who invented, developed and maintained this project for free in my leasure time for ~8 years, I hope I earned right to have a say in the features that're added to this project :).

-> The project can quite certainly grow to take that role, but it would require a new person to drive such a project.
Since the focus for that project would also be different and since it would most likely require large amounts of refactoring to fulfill such a new roll well, a feature-fork would probably be the best solution.

**Comment by Nukesor** [comment] 2023-05-23 21:14
> This is the Unix way.

Also, regarding the unix way :wink: : https://en.wikipedia.org/wiki/Unix_philosophy#Do_One_Thing_and_Do_It_Well

**Comment by fluffysquirrels** [comment] 2023-05-24 07:56
> Also, as the person who invented, developed and maintained this project for free in my leasure time for [~8](https://github.com/Nukesor/pueue-python-legacy/commit/81b738f337be0fba68f711f3cb1ba0937c3e0bb8) years, I hope I earned the right to have a say in the features that're added to this project :).

I find this very strange. You are the one with admin rights to this repo and crate, so of course you have the "rights" to do whatever you want in that sense. You released the code under the MIT license, so there almost no "rights" apart from that. There is no "earning" this, you always had this control.

By publishing some useful code as open-source you're directly inviting people to collaborate with you and contribute suggestions and code. If you don't want that any more (which I can personally understand), then you could archive the repo, announce that it's in maintenance mode, request for other maintainers, nominate a fork, etc.

-----

As for the architectural consequences of my suggestion, filtering by ID client-side in `pueue` would be, what ... 30 lines of code? 50 lines of code? These would just be in the status command, not core code so wouldn't really add complexity elsewhere. You can choose not to accept a PR for this if you want, but I don't think there are any architectural consequences at all.

-----

Regarding the Unix philosophy, you linked to the wiki section for "Do one thing and do it well", which was first described in approximately that form by [Doug McIlroy in 1978](https://en.wikipedia.org/wiki/Unix_philosophy#Origin). I think you're missing several important issues. McIlroy's very next bullet point is:

> Expect the output of every program to become the input to another, as yet unknown, program. Don't clutter output with extraneous information. Avoid stringently columnar or binary input formats. Don't insist on interactive input.

`pueue` violates this. By being hostile to programmability and scripting, you are preventing `pueue`'s output from being the input of another program. `pueue` returns 0 as its exit code when errors occur. `pueue` puts error messages on `stdout`. `pueue`'s output is by default not machine readable, although there are some options in some places for JSON output. Returning 0 as an exit code when errors occur is not part of a "vision" or "philosophy" for `pueue`, it's just a bug, which I can fix for you in a PR.

I interpret the Unix way in the modern era as each **command** or component should do one thing and do it well, and be easily combined with other components.

`busybox` is arguably a "program", it's certainly built as a single binary file, but it consists of many commands, and many of those are designed to do one thing. `busybox` commands (mostly standard POSIX utilities) combine well with other commands; they may be in one binary, but to me that's an implementation detail that I don't need to worry about as a user.

The genius of the Unix CLI, which has stood the test of time, was that it was programmable with shell scripts, and it allowed easy run-time combination of commands by a user. The alternative at the time was I expect to hand write exactly what you needed in a brand new program. So to delete all the JSON files in a directory tree I'd get out my text editor and write the source code for a compiled language program to do that for me. The Unix way would be `find . -name '*.json' | xargs rm`. And again, instead of accepting my 50-line PR to modify `pueue` to enable the second one, you're encouraging me to do the first one by suggesting I write my own Rust frontend to `pueue_lib`, all so I can query status by ID.

When I write software, both open and closed source, the most exciting part is always feedback from others and collaboration. People sometimes praise my software, often find bugs, and often want more features. A lot of this is unexpected and delightful. If you let other people contribute, the project may become more than you'd originally imagined, but that's OK.

**Comment by Nukesor** [comment] 2023-05-24 10:47
> By publishing some useful code as open-source you're directly inviting people to collaborate with you and contribute suggestions and code. If you don't want that any more (which I can personally understand), then you could archive the repo, announce that it's in maintenance mode, request for other maintainers, nominate a fork, etc.

I'm continuing my work on this project, but I stay true to the vision I have for this project.
This means that I accept some feature requests, but also that I'll reject some requests that don't match that vision, which in this case happens to be yours.

> As for the architectural consequences of my suggestion, filtering by ID client-side in pueue would be, what ... 30 lines of code? 50 lines of code?

Every single feature that is added to any project will allow people to do certain things and push it into a certain direction.
This is why every project manager should always analyze on whether a feature matches into a products scope or not.
In this case, this is a feature that would allow users to built more complex scripts on top of the `pueue` binary, further encouraging scripting, which just isn't what it has been designed for!
Just take the JSON output for example. It was designed for status bars!!! But people started using it as a entry point for scripting!

Suddenly one has a bastardized feature that's misused by a community that wants even more features to bastardize that feature even more.

`pueued`'s architecture isn't designed to be scriptable.
There's a global mutex lock for all state, processing logical requests happens within a main loop with small sleeps, which leads to small synchronization issues when there're concurrent or fast subsequent requests. The further `pueue` or `pueued` is being used for scripting, these design flaws will start to show. There were already a few workarounds/design refactorings I had to built to support scripting!
`pueue wait` was heavily driven by the need to work around this design flaw!

My biggest mistake was that I didn't see this coming at an earlier time and didn't prevented some other features from being merged. Either I discourage scripting and keep the architecture like it is, or I accept feature requests that encourage scripting and accept that I'll have to do a major storage layer refactoring and other architectural changes in the project.

As I said, it seems like it's time for a dedicated and dependable developer to either re-write or fork and refactor this project to create a project that's more programmatic in nature.

> Expect the output of every program to become the input to another, as yet unknown, program. Don't clutter output with extraneous information. Avoid stringently columnar or binary input formats. Don't insist on interactive input.

You're missing the point, I neither care about nor follow the Unix philosophy :D. I just quoted a very matching part of the philosophy you obey to contradict this feature request. By chance, it also happens to be one of the core design principles I try to obey, which I found quite matching.

Pueue was built for **human** interaction and I intent to focus on this. Scripting was never in the scope of this project and shifting the focus to that would go against that principle.

> When I write software, both open and closed source, the most exciting part is always feedback from others and collaboration. People sometimes praise my software, often find bugs, and often want more features. A lot of this is unexpected and delightful. If you let other people contribute, the project may become more than you'd originally imagined, but that's OK.

Really :D This is the most condecending comment I've received in years :D. You let it sound like I don't accept features in general or like I didn't work together with the community for the last decade of my life. I'm not sure what I should make of this comment.

Last but not least, speaking of bastardized feature creep. I just remembered there's another extremely ugly remainder of a temporary workaround feature that perfectly covers your usecase. Take a look at `pueue format-status`. This will allow you to do any filtering logic on status you like.

Blindly accepting feature requests lead this project to have such a weird feature state. This request finally convinced me to make it right and bring the project back on track of the original vision.

**Comment by Nukesor** [comment] 2023-05-28 18:11
Closing as wontdo, since this doesn't fit into the scope of the project.

The wanted behavior is achievable via the `format-status` subcommand. (Keep in mind: As described in the help text disclaimer, this might get removed sometime in the future)

**Closed by Nukesor** 2023-05-28 18:11 UTC
Labels: t: Feature
